
const products = [{
    id: 1,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 20,
},
{
    id: 2,
    srcImg: "img/slide_skor2.png",
    name: "Скор 250 ЕС к.э.",
    price: 200,
},
{
    id: 3,
    srcImg: "img/slide_skor.png",
    name: "Скор 250 ЕС к.э.",
    price: 589,
},
{
    id: 4,
    srcImg: "img/slide_pet2.png",
    name: "Петунія Софістика F1",
    price: 20,
},{
    id: 5,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 400,
},
{
    id: 6,
    srcImg: "img/slide_pet2.png",
    name: "Петунія Софістика F1",
    price: 589,
},
{
    id: 7,
    srcImg: "img/slide_skor2.png",
    name: "Скор 250 ЕС к.э.",
    price: 200,
},{
    id: 8,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 110,
},
{
    id: 9,
    srcImg: "img/slide_pet2.png",
    name: "Петунія Софістика F1",
    price: 340,
},
{
    id: 10,
    srcImg: "img/slide_pet.png",
    name: "Шевченська Софістика F1",
    price: 4220,
},
{
    id: 11,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 83,
},
{
    id: 12,
    srcImg: "img/slide_skor.png",
    name: "Скор 250 ЕС к.э.1",
    price: 534,
},
{
    id: 13,
    srcImg: "img/slide_skor2.png",
    name: "Скор 250 ЕС к.э.",
    price: 200,
},
{
    id: 14,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 3400,
},
{
    id: 15,
    srcImg: "img/slide_skor.png",
    name: "Шевченська Софістика F1",
    price: 2400,
},
{
    id: 16,
    srcImg: "img/slide_pet2.png",
    name: "Петунія Софістика F1",
    price: 183,
},
{
    id: 17,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 460,
},
{
    id: 18,
    srcImg: "img/slide_pet2.png",
    name: "Скор 250 ЕС к.э.",
    price: 2200,
},
{
    id: 19,
    srcImg: "img/slide_skor2.png",
    name: "Скор 250 ЕС к.э.",
    price: 200,
},
{
    id: 20,
    srcImg: "img/slide_pet.png",
    name: "Шевченська Софістика F5",
    price: 230,
},
{
    id: 21,
    srcImg: "img/slide_pet2.png",
    name: "Петунія Софістика F23",
    price: 1183,
},
{
    id: 22,
    srcImg: "img/slide_pet.png",
    name: "Шевченська Софістика F1",
    price: 4060,
},
{
    id: 23,
    srcImg: "img/slide_pet.png",
    name: "Петунія Софістика F1",
    price: 22,
},
{
    id: 24,
    srcImg: "img/slide_skor.png",
    name: "Скор 250 ЕС к.э.",
    price: 590,
},
]


